


export const FASKES_TYPES = {
    puskesmas: { label: "Puskesmas", emoji: "🏥", color: "green" },
    klinik: { label: "Klinik", emoji: "🏪", color: "blue" },
    rs: { label: "Rumah Sakit", emoji: "🏨", color: "red" },
};

export const CITIES = [
    { value: "indramayu", label: "Kab. Indramayu" },
    { value: "cirebon-kota", label: "Kota Cirebon" },
    { value: "cirebon-kab", label: "Kab. Cirebon" },
];

export const FASKES_DATA = [
    {
        id: "pkm-jatibarang",
        name: "Puskesmas Jatibarang",
        type: "puskesmas",
        city: "indramayu",
        address: "Jl. Raya Jatibarang No. 45, Kec. Jatibarang, Kab. Indramayu",
        phone: "0234-351234",
        hours: "Senin - Sabtu: 07.30 - 14.30 WIB",
        hasIGD: false,
        services: ["Poli Umum", "Poli Gigi", "KIA", "Laboratorium", "Farmasi"],
        mapsUrl: "https://maps.google.com/?q=-6.4792,108.3028",
    },
    {
        id: "pkm-sindang",
        name: "Puskesmas Sindang",
        type: "puskesmas",
        city: "indramayu",
        address: "Jl. Raya Sindang No. 12, Kec. Sindang, Kab. Indramayu",
        phone: "0234-275123",
        hours: "Senin - Sabtu: 07.30 - 14.30 WIB",
        hasIGD: true,
        services: ["Poli Umum", "Poli Gigi", "KIA", "IGD 24 Jam", "Rawat Inap"],
        mapsUrl: "https://maps.google.com/?q=-6.4554,108.3256",
    },
    {
        id: "rs-indramayu",
        name: "RSUD Indramayu",
        type: "rs",
        city: "indramayu",
        address: "Jl. Letjen Suprapto No. 1, Kec. Indramayu, Kab. Indramayu",
        phone: "0234-271552",
        hours: "24 Jam (IGD), Poli: Senin - Sabtu 08.00 - 14.00 WIB",
        hasIGD: true,
        services: ["IGD 24 Jam", "Rawat Inap", "ICU", "Radiologi", "Bedah", "Poli Spesialis"],
        mapsUrl: "https://maps.google.com/?q=-6.3273,108.3206",
    },
    {
        id: "klinik-medika-indramayu",
        name: "Klinik Pratama Medika",
        type: "klinik",
        city: "indramayu",
        address: "Jl. Pahlawan No. 88, Kec. Indramayu, Kab. Indramayu",
        phone: "0234-276890",
        hours: "Senin - Minggu: 08.00 - 21.00 WIB",
        hasIGD: false,
        services: ["Poli Umum", "Poli Gigi", "Lab Cepat", "Farmasi"],
        mapsUrl: "https://maps.google.com/?q=-6.3315,108.3250",
    },
    {
        id: "rs-gunung-jati",
        name: "RSUD Gunung Jati Cirebon",
        type: "rs",
        city: "cirebon-kota",
        address: "Jl. Kesambi No. 56, Kota Cirebon",
        phone: "0231-206330",
        hours: "24 Jam (IGD), Poli: Senin - Sabtu 08.00 - 14.00 WIB",
        hasIGD: true,
        services: ["IGD 24 Jam", "Rawat Inap", "ICU", "Bedah", "Hemodialisis", "Poli Spesialis"],
        mapsUrl: "https://maps.google.com/?q=-6.7320,108.5523",
    },
    {
        id: "rs-pelabuhan-cirebon",
        name: "RS Pelabuhan Cirebon",
        type: "rs",
        city: "cirebon-kota",
        address: "Jl. Sisingamangaraja No. 45, Kota Cirebon",
        phone: "0231-241168",
        hours: "24 Jam (IGD), Poli: Senin - Sabtu 08.00 - 15.00 WIB",
        hasIGD: true,
        services: ["IGD 24 Jam", "Rawat Inap", "Poli Umum", "Poli Spesialis", "Laboratorium"],
        mapsUrl: "https://maps.google.com/?q=-6.7115,108.5564",
    },
    {
        id: "pkm-waled",
        name: "Puskesmas Waled",
        type: "puskesmas",
        city: "cirebon-kab",
        address: "Jl. Raya Waled No. 23, Kec. Waled, Kab. Cirebon",
        phone: "0231-341567",
        hours: "Senin - Sabtu: 07.30 - 14.30 WIB",
        hasIGD: true,
        services: ["Poli Umum", "Poli Gigi", "KIA", "IGD", "Rawat Inap"],
        mapsUrl: "https://maps.google.com/?q=-6.7987,108.7234",
    },
    {
        id: "klinik-sehat-cirebon",
        name: "Klinik Sehat Sejahtera",
        type: "klinik",
        city: "cirebon-kota",
        address: "Jl. Kartini No. 15, Kota Cirebon",
        phone: "0231-209876",
        hours: "Senin - Minggu: 07.00 - 22.00 WIB",
        hasIGD: false,
        services: ["Poli Umum", "Poli Gigi", "Lab Cepat", "Vaksinasi", "Farmasi"],
        mapsUrl: "https://maps.google.com/?q=-6.7262,108.5517",
    },
];
